<form class="admin-form" action="{% if isCreate == true %}{{url('category/create')}}{% else %}{{url('category/save')}}{%endif%}" method="POST" id="admin-form">
  <div class="form-group">
    <label for="name">Category name:</label>
    <input type="text" class="form-control" id="name" name="name" value="{{newName}}" placeholder="e.g. Sports"/>
    <input type="hidden" class="form-control" id="id" name="id" value="{{newId}}" />
  </div>
  {% if isCreate == true %}
        <input type="submit" class="btn btn-primary" value="Submit">
  {%else %} 
        <input type="submit" value="Save" class="btn btn-primary"/>
        <a href="{{url('category')}}">Cancel</a>
  {% endif %}
</form>