<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="#">QuizUp Admin</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{url('login')}}">Login</a></li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<aside class="sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li role="presentation" class="active"><a href="#">Categories</a></li>
    <li role="presentation"><a href="#">Questions</a></li>
    <li role="presentation"><a href="#">Users</a></li>
    <li role="presentation"><a href="#">Teams</a></li>
  </ul>
</aside>