<form class="admin-form">
  <div class="form-group">
    <label for="text">Question:</label>
    <input type="text" class="form-control" name="text" placeholder="e.g. Sports">
    <label for="category">Question:</label>
    <select class="form-control" name="category">
      <option value="1"></option>
      <option value="2"></option>
      <option value="3"></option>
      <option value="4"></option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>