  {% include "partials/header.phtml" %}

  {% include "partials/nav-admin.phtml" %}

  <div class="dashboard">
    <div class="padded">
      <h1>List of categories</h1> 
      <a href="" class="btn btn-primary">Add New</a>
      {% include "partials/category-form.phtml" %}
      
      <h1>Questions</h1>
      <a href="" class="btn btn-primary">Add New Question</a>
      {% include "partials/question-form.phtml" %}
    </div>
    
  </div>
  
  
  
  {% include "partials/footer-admin.phtml" %}
</body>
</html>