  {% include "partials/header.phtml" %}

  {% include "partials/nav-admin.phtml" %}

  <div class="dashboard">
    <div class="padded">
      <h1>List of categories</h1> 
      <a href="" class="btn btn-primary">Add New</a>

      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
        
      

        {% for category in categories %}
          <tr>
            <td>{{category.id}}</td>
            <td>{{category.name}}</td>
            <td><a href="{{ url('category/update/'~category.id) }}"><i class="fa fa-edit"></i></a>   <a href="{{ url('category/delete/'~category.id) }}"><i class="fa fa-trash"></i></a></li></td>
          </tr>
        {% endfor %}    
      </table>
      {% include "partials/category-form.phtml" %}
      <h1>Questions</h1>
      <a href="" class="btn btn-primary">Add New Question</a>
      {% include "partials/question-form.phtml" %}
    </div>
    
  </div>
  
  
  
  {% include "partials/footer-admin.phtml" %}
</body>
</html>