  {% include "partials/header.phtml" %}

  {% include "partials/nav-admin.phtml" %}

  <div class="dashboard">
    <div class="padded">
      <h1>List of categories</h1> 
      <a href="#admin-form" class="btn btn-primary" id="addCategory">Add New</a>
      
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
        {% for category in categories %}
          <tr>
            <td>{{category.id}}</td>
            <td>{{category.name}}</td>
            <td><a href="{{ url('category/'~category.id) }}"><i class="fa fa-edit"></i></a>   <a href="{{ url('category/delete/'~category.id) }}"><i class="fa fa-trash"></i></a></li></td>
          </tr>
        {% endfor %}    
      </table>

      {% include "partials/category-form.phtml" %}
    
  </div>
  
  
  
  {% include "partials/footer-admin.phtml" %}
  {{ assets.outputJs() }}
</body>
</html>