  {% include "partials/header.phtml" %}

  {% include "partials/navigation.phtml" %}

  <section class="info-section">
      <div class="tcell">
        <h1>QuizUp</h1>
        <p class="info-description">
          The ultimate Pub Quiz Platform
        </p>
      </div>      
  </section>

  {% include "partials/events.phtml" %}

  <section class="history">
    <h1>Finished Events</h1>
    <p>Wanna see details about previous events?</p>
    <div class="center all-events-btn">
        <a class="show-more" href="#">Show history</a>
    </div>
  </section>
  
  {% include "partials/footer.phtml" %}
</body>
</html>